version: '3.8'

services:
  app:
    build: .
    container_name: nestjs_app
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_USER=prmAdmin
      - DATABASE_PASSWORD=prmAdmin123!
      - DATABASE_NAME=prm-postgres

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      - POSTGRES_USER=prmAdmin
      - POSTGRES_PASSWORD=prmAdmin123!
      - POSTGRES_DB=prm-postgres
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
